module.exports = {
    COMMUNNITY_CHAT:" COMMUNNITY_CHAT",
    USER_CONNECTED:"USER_CONNECTED",
    MESSAGE_RECEIVED:"MESSAGE_RECEIVED",
    MESSAGE_SENT:"",
    USER_DISCONNECTED:"",
    TYPING:"",
    LOGOUT:""
}